### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by phillip-toone** [senaite/senaite.ansible-playbook#11]
I am attempting to install senaite to a DigitalOcean virtual machine (Ubuntu 16.04 x64) for evaluation purposes. On the last step of the [Readme.md](https://github.com/senaite/senaite.ansible-playbook/blob/master/Readme.md) instructions

`ansible-playbook -i vagrant_hosts.cfg vagrant_playbook.yml`

I get the following error

> PLAY ***************************************************************************
> 
> TASK [setup] *******************************************************************
> fatal: [senaite]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}
> 
> PLAY RECAP *********************************************************************
> senaite                    : ok=0    changed=0    unreachable=1    failed=0

So I attempt to use the recommended -vvvv option like this

`ansible-playbook -vvvv -i vagrant_hosts.cfg vagrant_playbook.yml`

but get this error

> Using /root/senaite.ansible-playbook/ansible.cfg as config file
> Loaded callback default of type stdout, v2.0
> 1 plays in vagrant_playbook.yml
> 
> PLAY ***************************************************************************
> 
> TASK [setup] *******************************************************************
> <192.168.33.10> ESTABLISH SSH CONNECTION FOR USER: vagrant
> <192.168.33.10> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile=".vagrant/machines/app/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.33.10 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1539615108.63-270820612721758 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1539615108.63-270820612721758 )" )'
> fatal: [senaite]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/root/.ansible/cp/ansible-ssh-192.168.33.10-22-vagrant\" does not exist\r\ndebug2: resolving \"192.168.33.10\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 192.168.33.10 [192.168.33.10] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 192.168.33.10 port 22: No route to host\r\nssh: connect to host 192.168.33.10 port 22: No route to host\r\n", "unreachable": true}
> 
> PLAY RECAP *********************************************************************
> senaite                    : ok=0    changed=0    unreachable=1    failed=0

**Comment by ramonski** [comment]
Hi @phillip-toone, you need to add the IP of your Digital Ocean VM to the `hosts.cfg` file.
At the moment the local Vagrant IP `192.168.33.10` is used, which is a local network address and only valid when you run the Vagrant setup.

Best you follow these instructions: https://github.com/senaite/senaite.ansible-playbook#customizing
and configure the Digital Ocean VM as described here: https://github.com/senaite/senaite.ansible-playbook#build-a-custom-vm

**Comment by phillip-toone** [comment]
I have attempted to follow the instruction in the [Customizing](https://github.com/senaite/senaite.ansible-playbook#customizing) sections with the following 2 modifications:

### Modification 1

`git clone git@github.com:senaite/senaite.ansible-playbook.git`

gave me the following error

> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 

so I replaced it with

`git clone https://github.com/senaite/senaite.ansible-playbook.git`

### Modification 2

I modified the line in the hosts.cfg file that was originally

`senaite ansible_ssh_host=172.16.65.100 ansible_ssh_user=myuser ansible_ssh_private_key_file=~/.ssh/id_rsa`

to match the IP address of my machine

`senaite ansible_ssh_host=165.227.23.74 ansible_ssh_user=myuser ansible_ssh_private_key_file=~/.ssh/id_rsa`

I obtained this IP address using

`hostname -I`

which game me

> 165.227.23.74 10.46.0.7 192.168.33.1

### Attempt 1

I first attempted to run the playbook with

`ansible-playbook -i hosts.cfg playbook.yml`

which gave me the following error

> PLAY ***************************************************************************
> 
> TASK [setup] *******************************************************************
> fatal: [senaite]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}
> 
> PLAY RECAP *********************************************************************
> senaite                    : ok=0    changed=0    unreachable=1    failed=0

### Attempt 2

So again I attempted to use the -vvvv switch

`ansible-playbook -vvvv -i hosts.cfg playbook.yml`

but got the following error

> Using /root/my.senaite.playbook/ansible.cfg as config file
> Loaded callback default of type stdout, v2.0
> 1 plays in playbook.yml
> 
> PLAY ***************************************************************************
> 
> TASK [setup] *******************************************************************
> <165.227.23.74> ESTABLISH SSH CONNECTION FOR USER: myuser
> <165.227.23.74> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=myuser -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 165.227.23.74 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1539699427.25-97708652967698 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1539699427.25-97708652967698 )" )'
> fatal: [senaite]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/root/.ansible/cp/ansible-ssh-165.227.23.74-22-myuser\" does not exist\r\ndebug2: resolving \"165.227.23.74\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 165.227.23.74 [165.227.23.74] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 9995 ms remain after connect\r\ndebug1: permanently_set_uid: 0/0\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_rsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_rsa-cert type -1\r\ndebug1: Enabling compatibility mode for protocol 2.0\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.4\r\ndebug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.4 pat OpenSSH* compat 0x04000000\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to 165.227.23.74:22 as 'myuser'\r\ndebug3: hostkeys_foreach: reading file \"/root/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:3\r\ndebug3: load_hostkeys: loaded 1 keys from 165.227.23.74\r\ndebug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c\r\ndebug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: zlib@openssh.com,zlib,none\r\ndebug2: compression stoc: zlib@openssh.com,zlib,none\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1\r\ndebug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com\r\ndebug2: compression stoc: none,zlib@openssh.com\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256@libssh.org\r\ndebug1: kex: host key algorithm: ecdsa-sha2-nistp256\r\ndebug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: Server host key: ecdsa-sha2-nistp256 SHA256:gQSxfZenpXM8UFbpn5VnZxUOpuO99PJJTsKOKVxudeY\r\ndebug3: hostkeys_foreach: reading file \"/root/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:3\r\ndebug3: load_hostkeys: loaded 1 keys from 165.227.23.74\r\ndebug1: Host '165.227.23.74' is known and matches the ECDSA host key.\r\ndebug1: Found key in /root/.ssh/known_hosts:3\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug2: key: /root/.ssh/id_rsa ((nil)), explicit\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 7\r\ndebug1: SSH2_MSG_EXT_INFO received\r\ndebug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password\r\ndebug3: start over, passed a different list publickey,password\r\ndebug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: ,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Trying private key: /root/.ssh/id_rsa\r\nno such identity: /root/.ssh/id_rsa: No such file or directory\r\ndebug2: we did not send a packet, disable method\r\ndebug1: No more authentication methods to try.\r\nPermission denied (publickey,password).\r\n", "unreachable": true}
> 
> PLAY RECAP *********************************************************************
> senaite                    : ok=0    changed=0    unreachable=1    failed=0

**Comment by phillip-toone** [comment]
Okay, I have read up on keygen and have attempted to use this to correct the issue I am having but I am a bit lost in the different layers of machines.  I am working on a local machine that is physically in front of me.  I can log into my digitalocean server as root (or any other user) with either a passsword or a keygen without a problem.  Now I am attempting to use Ansible Playbook to build a virtual machine within the digitalocean machine I am logged into.  It seems to me that I need to created a keygen for the digitalocean user (root in my case) that is attempting to create the virtual machine.  To do this I apply the following command

`ssh-keygen -t rsa -b 4096`

This creates id_rsa and id_rsa.pub within a .ssh directory.  I create a my.senaite.playbook directory in the /root directory that contains the SENAITE Ansible Playbook files with the following command

`git clone https://github.com/senaite/senaite.ansible-playbook.git`

I also populate this directory with the ansible.cfg, configure.yml, hosts.cfg, playbook.yml, senaite.ansible-playbook files as described in [Readme.md](https://github.com/senaite/senaite.ansible-playbook/blob/master/Readme.md).  I modify the hosts.cfg file like this:

> [vm]
> senaite ansible_ssh_host=165.227.23.74 ansible_ssh_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa

Now I would expect the following command to use the information contained in the hosts.cfg along with the id_rsa file to build the virtual machine within the digitalocean machine I am logged into.  But I get an error that looks like a lot like the previous errors I have quoted.  What I am not doing right here?

**Comment by phillip-toone** [comment]
Okay, the following is a script I've created to run on a new digitalocean Ubuntu 16.04

Install updates:
```
apt update
apt install -y vagrant virtualbox-qt ansible
```
Set up  keygen
```
ssh-keygen
ssh-copy-id root@142.93.27.41
```
Clone repository
```
mkdir my.senaite.playbook
cd my.senaite.playbook
git clone https://github.com/senaite/senaite.ansible-playbook.git
```
Create ansible.cfg
```
> ansible.cfg
echo "[defaults]" >> ansible.cfg
echo "roles_path = senaite.ansible-playbook/roles" >> ansible.cfg
```
Create configure.yml
```
> configure.yml
echo 'plone_initial_password: "mysecret"' >> configure.yml
echo 'munin_admin_user: "admin"' >> configure.yml
echo 'munin_admin_password: "mysecret"' >> configure.yml
echo 'haproxy_stats_user: "admin"' >> configure.yml
echo 'haproxy_stats_pass: "mysecret"' >> configure.yml
echo 'supervisor_http_user: "admin"' >> configure.yml
echo 'supervisor_http_pass: "mysecret"' >> configure.yml
echo 'firewall_open_tcp_ports: [22, 25, 80, 443]' >> configure.yml
echo 'nginx_keepalive_timeout: "300"' >> configure.yml
```
Create hosts.cfg
```
myIP="$(hostname -I | awk '{print $1}')"
> hosts.cfg
echo "[vm]" >> hosts.cfg
echo "senaite ansible_ssh_host=$myIP ansible_ssh_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa" >> hosts.cfg
```
Create playbook.yml
```
> playbook.yml
echo "- hosts: vm" >> playbook.yml
echo "  become: yes" >> playbook.yml
echo "  become_method: sudo" >> playbook.yml
echo "  gather_facts: yes" >> playbook.yml
echo "  pre_tasks:" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_pre_tasks.yml" >> playbook.yml
echo "    # Include our onw overwrite variables" >> playbook.yml
echo "    - name: Include variables defined in `configure.yml`" >> playbook.yml
echo "      include_vars: configure.yml" >> playbook.yml
echo "      tags:" >> playbook.yml
echo "        - always" >> playbook.yml
echo "" >> playbook.yml
echo "  tasks:" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_base.yml" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_plone.yml" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_haproxy.yml" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_varnish.yml" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_nginx.yml" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_munin.yml" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_postfix.yml" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_security.yml" >> playbook.yml
echo "" >> playbook.yml
echo "  handlers:" >> playbook.yml
echo "    - include: senaite.ansible-playbook/senaite_handlers.yml" >> playbook.yml
```
Run playbook
```
ansible-playbook -i hosts.cfg playbook.yml
```
But I get the following error:
> PLAY ***************************************************************************
> 
> TASK [setup] *******************************************************************
> ok: [senaite]
> 
> TASK [include] *****************************************************************
> included: /root/my.senaite.playbook/senaite.ansible-playbook/senaite_pre_tasks.yml for senaite
> 
> TASK [debug] *******************************************************************
> ok: [senaite] => {
>     "msg": "******************** SENAITE PRE-TASKS [START] ********************"
> }
> 
> TASK [Include SENAITE configure variables `senaite_configure.yml`] *************
> fatal: [senaite]: FAILED! => {"changed": false, "failed": true, "file": "/root/my.senaite.playbook/senaite_configure.yml", "msg": "Source file not found."}
> 
> PLAY RECAP *********************************************************************
> senaite                    : ok=3    changed=0    unreachable=0    failed=1

Copying either configure.yml or senaite.ansible-playbook/senaite_configure.yml to senaite_configure.yml seems to fix this:

`cp senaite.ansible-playbook/senaite_configure.yml senaite_configure.yml`

or

`cp configure.yml senaite_configure.yml`

but results in the following error
> PLAY ***************************************************************************
> 
> TASK [setup] *******************************************************************
> ok: [senaite]
> 
> TASK [include] *****************************************************************
> included: /root/my.senaite.playbook/senaite.ansible-playbook/senaite_pre_tasks.yml for senaite
> 
> TASK [debug] *******************************************************************
> ok: [senaite] => {
>     "msg": "******************** SENAITE PRE-TASKS [START] ********************"
> }
> 
> TASK [Include SENAITE configure variables `senaite_configure.yml`] *************
> ok: [senaite]
> 
> TASK [Fail if Ansible version is too old] **************************************
> skipping: [senaite]
> 
> TASK [Setting variables for -> Ubuntu] *****************************************
> fatal: [senaite]: FAILED! => {"failed": true, "msg": "ERROR! No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}
> 
> PLAY RECAP *********************************************************************
> senaite                    : ok=4    changed=0    unreachable=0    failed=1

**Comment by ramonski** [comment]
Hi @phillip-toone, you do not have to install any software on the target (Digital Ocean) machine. You setup the `hosts.cfg` in your local senaite.ansible-playbook workspace and run `ansible-playbook -i hosts.cfg playbook.yml`. However, you need to verify that you can login via ssh and no password authentication to the target machine. Furthermore, `python` needs to be installed and the user you used to connect to the target is in the `sudoers` file (which means that you can do a `sudo su -` on your Digital Ocean server without being prompted for a password).

**Comment by phillip-toone** [comment]
You are right. I was attempting to accomplish this from within the digital ocean machine via ssh.  When I run the `ansible-playbook -i hosts.cfg playbook.yml` from my local machine everything goes well until it attempts the following task:

> TASK [Run SENAITE PLONE] **********************************************************************************************************************************************************************************************************************
> ERROR! the role 'plone.plone_server' was not found in /home/phillip/my.senaite.playbook/roles:/home/phillip/my.senaite.playbook/senaite.ansible-playbook/roles:/home/phillip/my.senaite.playbook
> 
> The error appears to have been in '/home/phillip/my.senaite.playbook/senaite.ansible-playbook/senaite_plone.yml': line 8, column 11, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
>   include_role:
>     name: plone.plone_server
>           ^ here
> 
> 	to retry, use: --limit @/home/phillip/my.senaite.playbook/playbook.retry
> 
> PLAY RECAP ************************************************************************************************************************************************************************************************************************************
> senaite                    : ok=11   changed=2    unreachable=0    failed=0   
>

**Comment by ramonski** [comment]
I'm closing this one @phillip-toone, because the described issues are all [ansible](https://docs.ansible.com) usage related.

**Comment by phillip-toone** [comment]
Thank you so much for all of your help. I would like to think that I have successfully installed this but I get the following when I attempt to view that site on a browser:

<h2>Site Error</h2> <p>An error was encountered while publishing this resource. </p> <p><strong>Resource not found</strong></p> Sorry, the requested resource does not exist.<p>Check the URL and try again.</p><p><b>Resource:</b> senaitelims GET</p> <hr noshade="noshade"/> <p>Troubleshooting Suggestions</p> <ul> <li>The URL may be incorrect.</li> <li>The parameters passed to this resource may be incorrect.</li> <li>A resource that this resource relies on may be encountering an error.</li> </ul> <p>For more detailed information about the error, please refer to the error log. </p> <p>If the error persists please contact the site maintainer. Thank you for your patience. </p>

I have created [these instructions](https://github.com/phillip-toone/hello-world/blob/master/senaite.md) for accomplishing this setup that I would like to share with this project once I have worked out all the bugs.

**Comment by phillip-toone** [comment]
I'm sorry but I don't think that I understand.  My server currently resides at the IP address 138.68.21.187 so I try to access it through [https://138.68.21.187](https://138.68.21.187).  I have also tried things like [https://138.68.21.187:8080](https://138.68.21.187:8080).  Am I supposed to set up this ID when I set up Plone or in one of the setup files used by the ansible-playbook.

**Comment by ramonski** [comment]
It is possible to access your instances directly via https://138.68.21.187/control_panel, so your SENAITE instances are running. It seems like your NGINX config is not correct.

**Comment by phillip-toone** [comment]
Yes, I can see a page that looks something like this;

## Administrative Links
ZMI	Plone Site	Plone Control Panel	Supervisor Control Panel	HAProxy Status	Munin Monitoring

## Control Panel
Supervisor
senaitelims_1 | ZMI
senaitelims_2 | ZMI

**Comment by phillip-toone** [comment]
I can also log into https://138.68.21.187/supervisor/ and https://138.68.21.187/munin/

**Comment by phillip-toone** [comment]
Okay, I just figured it out.  I need to go here: https://138.68.21.187/senaitelims_1/login
