### ISSUE TITLE
buildout-cache.tar.bz2 for Plone 4.3.15 not available

### ISSUE THREAD

**Issue by juangallostra** [senaite/senaite.ansible-playbook#2]
## Steps to reproduce

Try to setup a SENAITE vm using the ansible-playbook.

## Current behavior

The setup fails when trying to download `buildout-cache.tar.bz2` from http://dist.plone.org/release/4.3.15/  because the file cannot be found. Maybe they have removed it recently or temporaly? The file does exist for previous and posterior Plone versions

## Expected behavior

The setup finishes without errors and everything is setup properly.
Changing the version in https://github.com/senaite/senaite.ansible-playbook/blob/8e73c2428736dd54b38d037f30acfa9751e7b91e/senaite_configure.yml#L255 solves the issue.

## Screenshot (optional)

It seems that `buildout-cache.tar.bz2` has been removed for Plone 4.3.15.

![seleccio_052](https://user-images.githubusercontent.com/9968427/42096875-d2afec42-7bb6-11e8-92e8-596e227b2bb4.png)

However, it is available for Plone 4.3.17

![seleccio_051](https://user-images.githubusercontent.com/9968427/42096880-d75cac1c-7bb6-11e8-9fab-8940cc9ecd85.png)

**Comment by juangallostra** [comment]
@ramonski what's your opinion on this? Should we update Plone's version in senaite.ansible-playbook/senaite_configure.yml or we shouldn't worry about it?

**Comment by ramonski** [comment]
Hi @juangallostra, I think we should go for 4.3.17 or maybe even provide a custom built `buildout-cache.tar.bz2` on one of http://downloads.senaite.com?
In any case, could you please do a PR for this?

We need to keep in mind that Plone 4.3.17 requires `lxml=3.6.0` and we need to update our custom `buildout`  configs here: https://github.com/senaite/senaite.core/blob/master/buildout.cfg#L100
